version: '3.9'
services:
#  back:
#    build:
#      context: server
#      dockerfile: ./Dockerfile
#    ports:
#      - '3333:3333'
#    restart: always
#    env_file:
#      - .env
  frontend:
    build:
      context: front
      dockerfile: ./Dockerfile
      args:
        BACKEND_URL: ${BACKEND_URL}
    ports:
      - '8888:8888'
    restart: always