version: '3.9'
services:
  back:
    build:
      context: server
      dockerfile: ./Dockerfile
    ports:
      - '8050:8050'
    restart: always
    env_file:
      - .env
  frontend:
    build:
      context: front
      dockerfile: ./Dockerfile
      args:
        BACKEND_URL: ${BACKEND_URL}
    ports:
      - '8888:8888'
    restart: always
  nginx:
    depends_on:
      - frontend
      - back
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
      args:
        NGINX_PORT: 80
        FRONTEND_PORT: 8888
        BACKEND_PORT: ${PORT}
    ports:
      - '80:80'
    restart: always